version: "3.8"

services:
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    container_name: client
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      - server

  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: server
    ports:
      - "8000:8000"
      - "1080:1080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge